package cn.henu.dao;

import cn.henu.pojo.Ability;
import java.util.List;

public interface AbilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer abilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated
     */
    int insert(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated
     */
    Ability selectByPrimaryKey(Integer abilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated
     */
    List<Ability> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ability record);
}