package cn.henu.dao;

import cn.henu.pojo.Articlecategoryref;
import java.util.List;

public interface ArticlecategoryrefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecategoryref
     *
     * @mbg.generated
     */
    int insert(Articlecategoryref record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecategoryref
     *
     * @mbg.generated
     */
    List<Articlecategoryref> selectAll();

    List<Articlecategoryref> selectByCategoryId(int categoryId);

    Articlecategoryref selectByArticleId(int articleId);
    int deleteByCategoryId(int categoryId);
    int deleteByArticleId(int articleId);
    int updateCategoryAndArticleByArticleId(Articlecategoryref articlecategoryref);
}