package cn.henu.dao;

import cn.henu.pojo.Comment;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    List<Comment> selectAll();

    List<Comment> selectByArticleId(int article_id);

    @Delete("delete from comment where comment_id=#{comment_id}")
    int delCommentById(int comment_id);

    @Delete("delete from comment where article_id=#{article_id}")
    int delCommentByArticleId(int article_id);


    @Select("select * from comment")
    List<Comment> countComm();

    Comment findCommById(int comment_id);
}