package cn.henu.dao;

import cn.henu.pojo.Photo;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface PhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated
     */
    int insert(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated
     */
    Photo selectByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated
     */
    List<Photo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Photo record);

    @Select("select * from photo where photo_status =1")
    public List<Photo> countPhotos();
}