package cn.henu.dao;

import cn.henu.pojo.Saying;
import java.util.List;

public interface SayingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saying
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sayingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saying
     *
     * @mbg.generated
     */
    int insert(Saying record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saying
     *
     * @mbg.generated
     */
    Saying selectByPrimaryKey(Integer sayingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saying
     *
     * @mbg.generated
     */
    List<Saying> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saying
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Saying record);
}