package cn.henu.dao;

import cn.henu.pojo.Timeline;
import java.util.List;

public interface TimelineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer timelineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbg.generated
     */
    int insert(Timeline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbg.generated
     */
    Timeline selectByPrimaryKey(Integer timelineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbg.generated
     */
    List<Timeline> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Timeline record);
}