package cn.henu.pojo;

import java.util.Date;

public class Ability {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.ability_id
     *
     * @mbg.generated
     */
    private Integer abilityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.ability_name
     *
     * @mbg.generated
     */
    private String abilityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.ability_num
     *
     * @mbg.generated
     */
    private String abilityNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.ability_update_time
     *
     * @mbg.generated
     */
    private Date abilityUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.ability_id
     *
     * @return the value of ability.ability_id
     *
     * @mbg.generated
     */
    public Integer getAbilityId() {
        return abilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.ability_id
     *
     * @param abilityId the value for ability.ability_id
     *
     * @mbg.generated
     */
    public void setAbilityId(Integer abilityId) {
        this.abilityId = abilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.user_id
     *
     * @return the value of ability.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.user_id
     *
     * @param userId the value for ability.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.ability_name
     *
     * @return the value of ability.ability_name
     *
     * @mbg.generated
     */
    public String getAbilityName() {
        return abilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.ability_name
     *
     * @param abilityName the value for ability.ability_name
     *
     * @mbg.generated
     */
    public void setAbilityName(String abilityName) {
        this.abilityName = abilityName == null ? null : abilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.ability_num
     *
     * @return the value of ability.ability_num
     *
     * @mbg.generated
     */
    public String getAbilityNum() {
        return abilityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.ability_num
     *
     * @param abilityNum the value for ability.ability_num
     *
     * @mbg.generated
     */
    public void setAbilityNum(String abilityNum) {
        this.abilityNum = abilityNum == null ? null : abilityNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.ability_update_time
     *
     * @return the value of ability.ability_update_time
     *
     * @mbg.generated
     */
    public Date getAbilityUpdateTime() {
        return abilityUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.ability_update_time
     *
     * @param abilityUpdateTime the value for ability.ability_update_time
     *
     * @mbg.generated
     */
    public void setAbilityUpdateTime(Date abilityUpdateTime) {
        this.abilityUpdateTime = abilityUpdateTime;
    }
}