package cn.henu.pojo;

import java.util.Date;

public class Article implements Comparable<Article>{


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_summary
     *
     * @mbg.generated
     */
    private String articleSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_like
     *
     * @mbg.generated
     */
    private Integer articleLike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_comment
     *
     * @mbg.generated
     */
    private Integer articleComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_click
     *
     * @mbg.generated
     */
    private Integer articleClick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_keyword
     *
     * @mbg.generated
     */
    private String articleKeyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_updatetime
     *
     * @mbg.generated
     */
    private Date articleUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_createtime
     *
     * @mbg.generated
     */
    private Date articleCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_status
     *
     * @mbg.generated
     */
    private Integer articleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_image
     *
     * @mbg.generated
     */
    private String articleImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_id
     *
     * @return the value of article.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_id
     *
     * @param userId the value for article.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_summary
     *
     * @return the value of article.article_summary
     *
     * @mbg.generated
     */
    public String getArticleSummary() {
        return articleSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_summary
     *
     * @param articleSummary the value for article.article_summary
     *
     * @mbg.generated
     */
    public void setArticleSummary(String articleSummary) {
        this.articleSummary = articleSummary == null ? null : articleSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_like
     *
     * @return the value of article.article_like
     *
     * @mbg.generated
     */
    public Integer getArticleLike() {
        return articleLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_like
     *
     * @param articleLike the value for article.article_like
     *
     * @mbg.generated
     */
    public void setArticleLike(Integer articleLike) {
        this.articleLike = articleLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_comment
     *
     * @return the value of article.article_comment
     *
     * @mbg.generated
     */
    public Integer getArticleComment() {
        return articleComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_comment
     *
     * @param articleComment the value for article.article_comment
     *
     * @mbg.generated
     */
    public void setArticleComment(Integer articleComment) {
        this.articleComment = articleComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_click
     *
     * @return the value of article.article_click
     *
     * @mbg.generated
     */
    public Integer getArticleClick() {
        return articleClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_click
     *
     * @param articleClick the value for article.article_click
     *
     * @mbg.generated
     */
    public void setArticleClick(Integer articleClick) {
        this.articleClick = articleClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_keyword
     *
     * @return the value of article.article_keyword
     *
     * @mbg.generated
     */
    public String getArticleKeyword() {
        return articleKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_keyword
     *
     * @param articleKeyword the value for article.article_keyword
     *
     * @mbg.generated
     */
    public void setArticleKeyword(String articleKeyword) {
        this.articleKeyword = articleKeyword == null ? null : articleKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_updatetime
     *
     * @return the value of article.article_updatetime
     *
     * @mbg.generated
     */
    public Date getArticleUpdatetime() {
        return articleUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_updatetime
     *
     * @param articleUpdatetime the value for article.article_updatetime
     *
     * @mbg.generated
     */
    public void setArticleUpdatetime(Date articleUpdatetime) {
        this.articleUpdatetime = articleUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_createtime
     *
     * @return the value of article.article_createtime
     *
     * @mbg.generated
     */
    public Date getArticleCreatetime() {
        return articleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_createtime
     *
     * @param articleCreatetime the value for article.article_createtime
     *
     * @mbg.generated
     */
    public void setArticleCreatetime(Date articleCreatetime) {
        this.articleCreatetime = articleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_status
     *
     * @return the value of article.article_status
     *
     * @mbg.generated
     */
    public Integer getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_status
     *
     * @param articleStatus the value for article.article_status
     *
     * @mbg.generated
     */
    public void setArticleStatus(Integer articleStatus) {
        this.articleStatus = articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_image
     *
     * @return the value of article.article_image
     *
     * @mbg.generated
     */
    public String getArticleImage() {
        return articleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_image
     *
     * @param articleImage the value for article.article_image
     *
     * @mbg.generated
     */
    public void setArticleImage(String articleImage) {
        this.articleImage = articleImage == null ? null : articleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbg.generated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbg.generated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }
    @Override
    public String toString() {
        return "Article{" +
                "articleId=" + articleId +
                ", userId=" + userId +
                ", articleTitle='" + articleTitle + '\'' +
                ", articleSummary='" + articleSummary + '\'' +
                ", articleLike=" + articleLike +
                ", articleComment=" + articleComment +
                ", articleClick=" + articleClick +
                ", articleKeyword='" + articleKeyword + '\'' +
                ", articleUpdatetime=" + articleUpdatetime +
                ", articleCreatetime=" + articleCreatetime +
                ", articleStatus=" + articleStatus +
                ", articleImage='" + articleImage + '\'' +
                ", articleContent='" + articleContent + '\'' +
                '}';
    }

    @Override
    public int compareTo(Article o) {
        return o.getArticleClick()-this.getArticleClick();
    }
}