package cn.henu.pojo;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_pid
     *
     * @mbg.generated
     */
    private Integer categoryPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_desc
     *
     * @mbg.generated
     */
    private String categoryDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_img
     *
     * @mbg.generated
     */
    private String categoryImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_status
     *
     * @mbg.generated
     */
    private Integer categoryStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_pid
     *
     * @return the value of category.category_pid
     *
     * @mbg.generated
     */
    public Integer getCategoryPid() {
        return categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_pid
     *
     * @param categoryPid the value for category.category_pid
     *
     * @mbg.generated
     */
    public void setCategoryPid(Integer categoryPid) {
        this.categoryPid = categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_desc
     *
     * @return the value of category.category_desc
     *
     * @mbg.generated
     */
    public String getCategoryDesc() {
        return categoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_desc
     *
     * @param categoryDesc the value for category.category_desc
     *
     * @mbg.generated
     */
    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc == null ? null : categoryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_img
     *
     * @return the value of category.category_img
     *
     * @mbg.generated
     */
    public String getCategoryImg() {
        return categoryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_img
     *
     * @param categoryImg the value for category.category_img
     *
     * @mbg.generated
     */
    public void setCategoryImg(String categoryImg) {
        this.categoryImg = categoryImg == null ? null : categoryImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.user_id
     *
     * @return the value of category.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.user_id
     *
     * @param userId the value for category.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_status
     *
     * @return the value of category.category_status
     *
     * @mbg.generated
     */
    public Integer getCategoryStatus() {
        return categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_status
     *
     * @param categoryStatus the value for category.category_status
     *
     * @mbg.generated
     */
    public void setCategoryStatus(Integer categoryStatus) {
        this.categoryStatus = categoryStatus;
    }
}