package cn.henu.pojo;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable , Comparable<Comment> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_name
     *
     * @mbg.generated
     */
    private String commentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_qq
     *
     * @mbg.generated
     */
    private String commentQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbg.generated
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_head
     *
     * @mbg.generated
     */
    private String commentHead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_ip
     *
     * @mbg.generated
     */
    private String commentIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_create_time
     *
     * @mbg.generated
     */
    private Date commentCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.article_id
     *
     * @return the value of comment.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.article_id
     *
     * @param articleId the value for comment.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_name
     *
     * @return the value of comment.comment_name
     *
     * @mbg.generated
     */
    public String getCommentName() {
        return commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_name
     *
     * @param commentName the value for comment.comment_name
     *
     * @mbg.generated
     */
    public void setCommentName(String commentName) {
        this.commentName = commentName == null ? null : commentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_qq
     *
     * @return the value of comment.comment_qq
     *
     * @mbg.generated
     */
    public String getCommentQq() {
        return commentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_qq
     *
     * @param commentQq the value for comment.comment_qq
     *
     * @mbg.generated
     */
    public void setCommentQq(String commentQq) {
        this.commentQq = commentQq == null ? null : commentQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     *
     * @mbg.generated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     *
     * @mbg.generated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_head
     *
     * @return the value of comment.comment_head
     *
     * @mbg.generated
     */
    public String getCommentHead() {
        return commentHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_head
     *
     * @param commentHead the value for comment.comment_head
     *
     * @mbg.generated
     */
    public void setCommentHead(String commentHead) {
        this.commentHead = commentHead == null ? null : commentHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_ip
     *
     * @return the value of comment.comment_ip
     *
     * @mbg.generated
     */
    public String getCommentIp() {
        return commentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_ip
     *
     * @param commentIp the value for comment.comment_ip
     *
     * @mbg.generated
     */
    public void setCommentIp(String commentIp) {
        this.commentIp = commentIp == null ? null : commentIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_create_time
     *
     * @return the value of comment.comment_create_time
     *
     * @mbg.generated
     */
    public Date getCommentCreateTime() {
        return commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_create_time
     *
     * @param commentCreateTime the value for comment.comment_create_time
     *
     * @mbg.generated
     */
    public void setCommentCreateTime(Date commentCreateTime) {
        this.commentCreateTime = commentCreateTime;
    }

    @Override
    public String toString() {
        return "Comment{" +
                "commentId=" + commentId +
                ", articleId=" + articleId +
                ", commentName='" + commentName + '\'' +
                ", commentQq='" + commentQq + '\'' +
                ", commentContent='" + commentContent + '\'' +
                ", commentHead='" + commentHead + '\'' +
                ", commentIp='" + commentIp + '\'' +
                ", commentCreateTime=" + commentCreateTime +
                '}';
    }

    @Override
    public int compareTo(Comment o) {
        int i=this.getArticleId()-o.getArticleId();
        if(i==0){
            return o.getCommentCreateTime().toString().compareTo(this.getCommentCreateTime().toString());
        }
        return i;
    }
}