package cn.henu.pojo;

import java.util.Date;

public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_id
     *
     * @mbg.generated
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_url
     *
     * @mbg.generated
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_name
     *
     * @mbg.generated
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_img
     *
     * @mbg.generated
     */
    private String linkImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_ownername
     *
     * @mbg.generated
     */
    private String linkOwnername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_update_time
     *
     * @mbg.generated
     */
    private Date linkUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_create_time
     *
     * @mbg.generated
     */
    private Date linkCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_status
     *
     * @mbg.generated
     */
    private Integer linkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_id
     *
     * @return the value of link.link_id
     *
     * @mbg.generated
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_id
     *
     * @param linkId the value for link.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_url
     *
     * @return the value of link.link_url
     *
     * @mbg.generated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_url
     *
     * @param linkUrl the value for link.link_url
     *
     * @mbg.generated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_name
     *
     * @return the value of link.link_name
     *
     * @mbg.generated
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_name
     *
     * @param linkName the value for link.link_name
     *
     * @mbg.generated
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_img
     *
     * @return the value of link.link_img
     *
     * @mbg.generated
     */
    public String getLinkImg() {
        return linkImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_img
     *
     * @param linkImg the value for link.link_img
     *
     * @mbg.generated
     */
    public void setLinkImg(String linkImg) {
        this.linkImg = linkImg == null ? null : linkImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_ownername
     *
     * @return the value of link.link_ownername
     *
     * @mbg.generated
     */
    public String getLinkOwnername() {
        return linkOwnername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_ownername
     *
     * @param linkOwnername the value for link.link_ownername
     *
     * @mbg.generated
     */
    public void setLinkOwnername(String linkOwnername) {
        this.linkOwnername = linkOwnername == null ? null : linkOwnername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_update_time
     *
     * @return the value of link.link_update_time
     *
     * @mbg.generated
     */
    public Date getLinkUpdateTime() {
        return linkUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_update_time
     *
     * @param linkUpdateTime the value for link.link_update_time
     *
     * @mbg.generated
     */
    public void setLinkUpdateTime(Date linkUpdateTime) {
        this.linkUpdateTime = linkUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_create_time
     *
     * @return the value of link.link_create_time
     *
     * @mbg.generated
     */
    public Date getLinkCreateTime() {
        return linkCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_create_time
     *
     * @param linkCreateTime the value for link.link_create_time
     *
     * @mbg.generated
     */
    public void setLinkCreateTime(Date linkCreateTime) {
        this.linkCreateTime = linkCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_status
     *
     * @return the value of link.link_status
     *
     * @mbg.generated
     */
    public Integer getLinkStatus() {
        return linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_status
     *
     * @param linkStatus the value for link.link_status
     *
     * @mbg.generated
     */
    public void setLinkStatus(Integer linkStatus) {
        this.linkStatus = linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.user_id
     *
     * @return the value of link.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.user_id
     *
     * @param userId the value for link.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Link{" +
                "linkId=" + linkId +
                ", linkUrl='" + linkUrl + '\'' +
                ", linkName='" + linkName + '\'' +
                ", linkImg='" + linkImg + '\'' +
                ", linkOwnername='" + linkOwnername + '\'' +
                ", linkUpdateTime=" + linkUpdateTime +
                ", linkCreateTime=" + linkCreateTime +
                ", linkStatus=" + linkStatus +
                ", userId=" + userId +
                '}';
    }
}