package cn.henu.pojo;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_id
     *
     * @mbg.generated
     */
    private Integer noticeId;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_content
     *
     * @mbg.generated
     */
    private String noticeContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_update_time
     *
     * @mbg.generated
     */
    private Date noticeUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_status
     *
     * @mbg.generated
     */
    private Integer noticeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_id
     *
     * @return the value of notice.notice_id
     *
     * @mbg.generated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_id
     *
     * @param noticeId the value for notice.notice_id
     *
     * @mbg.generated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_content
     *
     * @return the value of notice.notice_content
     *
     * @mbg.generated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_content
     *
     * @param noticeContent the value for notice.notice_content
     *
     * @mbg.generated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_update_time
     *
     * @return the value of notice.notice_update_time
     *
     * @mbg.generated
     */
    public Date getNoticeUpdateTime() {
        return noticeUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_update_time
     *
     * @param noticeUpdateTime the value for notice.notice_update_time
     *
     * @mbg.generated
     */
    public void setNoticeUpdateTime(Date noticeUpdateTime) {
        this.noticeUpdateTime = noticeUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_status
     *
     * @return the value of notice.notice_status
     *
     * @mbg.generated
     */
    public Integer getNoticeStatus() {
        return noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_status
     *
     * @param noticeStatus the value for notice.notice_status
     *
     * @mbg.generated
     */
    public void setNoticeStatus(Integer noticeStatus) {
        this.noticeStatus = noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.user_id
     *
     * @return the value of notice.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.user_id
     *
     * @param userId the value for notice.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    @Override
    public String toString() {
        return "Notice{" +
                "noticeId=" + noticeId +
                ", noticeContent='" + noticeContent + '\'' +
                ", noticeUpdateTime=" + noticeUpdateTime +
                ", noticeStatus=" + noticeStatus +
                ", userId=" + userId +
                '}';
    }

}