package cn.henu.pojo;

import java.util.Comparator;
import java.util.Date;

public class Photo implements Comparable<Photo> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_id
     *
     * @mbg.generated
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_url
     *
     * @mbg.generated
     */
    private String photoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_title
     *
     * @mbg.generated
     */
    private String photoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_desc
     *
     * @mbg.generated
     */
    private String photoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_update_time
     *
     * @mbg.generated
     */
    private Date photoUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_create_time
     *
     * @mbg.generated
     */
    private Date photoCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_status
     *
     * @mbg.generated
     */
    private Integer photoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_id
     *
     * @return the value of photo.photo_id
     *
     * @mbg.generated
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_id
     *
     * @param photoId the value for photo.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_url
     *
     * @return the value of photo.photo_url
     *
     * @mbg.generated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_url
     *
     * @param photoUrl the value for photo.photo_url
     *
     * @mbg.generated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_title
     *
     * @return the value of photo.photo_title
     *
     * @mbg.generated
     */
    public String getPhotoTitle() {
        return photoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_title
     *
     * @param photoTitle the value for photo.photo_title
     *
     * @mbg.generated
     */
    public void setPhotoTitle(String photoTitle) {
        this.photoTitle = photoTitle == null ? null : photoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_desc
     *
     * @return the value of photo.photo_desc
     *
     * @mbg.generated
     */
    public String getPhotoDesc() {
        return photoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_desc
     *
     * @param photoDesc the value for photo.photo_desc
     *
     * @mbg.generated
     */
    public void setPhotoDesc(String photoDesc) {
        this.photoDesc = photoDesc == null ? null : photoDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_update_time
     *
     * @return the value of photo.photo_update_time
     *
     * @mbg.generated
     */
    public Date getPhotoUpdateTime() {
        return photoUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_update_time
     *
     * @param photoUpdateTime the value for photo.photo_update_time
     *
     * @mbg.generated
     */
    public void setPhotoUpdateTime(Date photoUpdateTime) {
        this.photoUpdateTime = photoUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_create_time
     *
     * @return the value of photo.photo_create_time
     *
     * @mbg.generated
     */
    public Date getPhotoCreateTime() {
        return photoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_create_time
     *
     * @param photoCreateTime the value for photo.photo_create_time
     *
     * @mbg.generated
     */
    public void setPhotoCreateTime(Date photoCreateTime) {
        this.photoCreateTime = photoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_status
     *
     * @return the value of photo.photo_status
     *
     * @mbg.generated
     */
    public Integer getPhotoStatus() {
        return photoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_status
     *
     * @param photoStatus the value for photo.photo_status
     *
     * @mbg.generated
     */
    public void setPhotoStatus(Integer photoStatus) {
        this.photoStatus = photoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.user_id
     *
     * @return the value of photo.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.user_id
     *
     * @param userId the value for photo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

	@Override
	public String toString() {
		return "Photo [photoId=" + photoId + ", photoUrl=" + photoUrl + ", photoTitle=" + photoTitle + ", photoDesc="
				+ photoDesc + ", photoUpdateTime=" + photoUpdateTime + ", photoCreateTime=" + photoCreateTime
				+ ", photoStatus=" + photoStatus + ", userId=" + userId + "]";
	}

    @Override
    public int compareTo(Photo o) {
        return o.getPhotoId()-this.getPhotoId();
    }
}