package cn.henu.pojo;

import java.util.Date;

public class Saying {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.saying_id
     *
     * @mbg.generated
     */
    private Integer sayingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.saying_author
     *
     * @mbg.generated
     */
    private String sayingAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.saying_content
     *
     * @mbg.generated
     */
    private String sayingContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.saying_update_time
     *
     * @mbg.generated
     */
    private Date sayingUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.saying_create_time
     *
     * @mbg.generated
     */
    private Date sayingCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.saying_status
     *
     * @mbg.generated
     */
    private Integer sayingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saying.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.saying_id
     *
     * @return the value of saying.saying_id
     *
     * @mbg.generated
     */
    public Integer getSayingId() {
        return sayingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.saying_id
     *
     * @param sayingId the value for saying.saying_id
     *
     * @mbg.generated
     */
    public void setSayingId(Integer sayingId) {
        this.sayingId = sayingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.saying_author
     *
     * @return the value of saying.saying_author
     *
     * @mbg.generated
     */
    public String getSayingAuthor() {
        return sayingAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.saying_author
     *
     * @param sayingAuthor the value for saying.saying_author
     *
     * @mbg.generated
     */
    public void setSayingAuthor(String sayingAuthor) {
        this.sayingAuthor = sayingAuthor == null ? null : sayingAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.saying_content
     *
     * @return the value of saying.saying_content
     *
     * @mbg.generated
     */
    public String getSayingContent() {
        return sayingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.saying_content
     *
     * @param sayingContent the value for saying.saying_content
     *
     * @mbg.generated
     */
    public void setSayingContent(String sayingContent) {
        this.sayingContent = sayingContent == null ? null : sayingContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.saying_update_time
     *
     * @return the value of saying.saying_update_time
     *
     * @mbg.generated
     */
    public Date getSayingUpdateTime() {
        return sayingUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.saying_update_time
     *
     * @param sayingUpdateTime the value for saying.saying_update_time
     *
     * @mbg.generated
     */
    public void setSayingUpdateTime(Date sayingUpdateTime) {
        this.sayingUpdateTime = sayingUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.saying_create_time
     *
     * @return the value of saying.saying_create_time
     *
     * @mbg.generated
     */
    public Date getSayingCreateTime() {
        return sayingCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.saying_create_time
     *
     * @param sayingCreateTime the value for saying.saying_create_time
     *
     * @mbg.generated
     */
    public void setSayingCreateTime(Date sayingCreateTime) {
        this.sayingCreateTime = sayingCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.saying_status
     *
     * @return the value of saying.saying_status
     *
     * @mbg.generated
     */
    public Integer getSayingStatus() {
        return sayingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.saying_status
     *
     * @param sayingStatus the value for saying.saying_status
     *
     * @mbg.generated
     */
    public void setSayingStatus(Integer sayingStatus) {
        this.sayingStatus = sayingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saying.user_id
     *
     * @return the value of saying.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saying.user_id
     *
     * @param userId the value for saying.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}