package cn.henu.pojo;

import java.util.Date;

public class Timeline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.timeline_id
     *
     * @mbg.generated
     */
    private Integer timelineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.timeline_title
     *
     * @mbg.generated
     */
    private String timelineTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.timeline_desc
     *
     * @mbg.generated
     */
    private String timelineDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.timeline_update_time
     *
     * @mbg.generated
     */
    private Date timelineUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.timeline_status
     *
     * @mbg.generated
     */
    private Integer timelineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.timeline_id
     *
     * @return the value of timeline.timeline_id
     *
     * @mbg.generated
     */
    public Integer getTimelineId() {
        return timelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.timeline_id
     *
     * @param timelineId the value for timeline.timeline_id
     *
     * @mbg.generated
     */
    public void setTimelineId(Integer timelineId) {
        this.timelineId = timelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.timeline_title
     *
     * @return the value of timeline.timeline_title
     *
     * @mbg.generated
     */
    public String getTimelineTitle() {
        return timelineTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.timeline_title
     *
     * @param timelineTitle the value for timeline.timeline_title
     *
     * @mbg.generated
     */
    public void setTimelineTitle(String timelineTitle) {
        this.timelineTitle = timelineTitle == null ? null : timelineTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.timeline_desc
     *
     * @return the value of timeline.timeline_desc
     *
     * @mbg.generated
     */
    public String getTimelineDesc() {
        return timelineDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.timeline_desc
     *
     * @param timelineDesc the value for timeline.timeline_desc
     *
     * @mbg.generated
     */
    public void setTimelineDesc(String timelineDesc) {
        this.timelineDesc = timelineDesc == null ? null : timelineDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.timeline_update_time
     *
     * @return the value of timeline.timeline_update_time
     *
     * @mbg.generated
     */
    public Date getTimelineUpdateTime() {
        return timelineUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.timeline_update_time
     *
     * @param timelineUpdateTime the value for timeline.timeline_update_time
     *
     * @mbg.generated
     */
    public void setTimelineUpdateTime(Date timelineUpdateTime) {
        this.timelineUpdateTime = timelineUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.timeline_status
     *
     * @return the value of timeline.timeline_status
     *
     * @mbg.generated
     */
    public Integer getTimelineStatus() {
        return timelineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.timeline_status
     *
     * @param timelineStatus the value for timeline.timeline_status
     *
     * @mbg.generated
     */
    public void setTimelineStatus(Integer timelineStatus) {
        this.timelineStatus = timelineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.user_id
     *
     * @return the value of timeline.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.user_id
     *
     * @param userId the value for timeline.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}